# Generated by Django 3.1.3 on 2020-12-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
    ]
